# Generated by Django 5.1.6 on 2025-02-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_brand'),
        ('Shop', '0006_remove_tbl_product_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_brand',
        ),
    ]
