# Generated by Django 5.1.6 on 2025-02-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_brand'),
        ('Shop', '0007_remove_tbl_stock_product_delete_tbl_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='tbl_brand',
        ),
        migrations.DeleteModel(
            name='tbl_category',
        ),
        migrations.DeleteModel(
            name='tbl_subcategory',
        ),
    ]
