# Generated by Django 5.1.4 on 2025-01-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_tbl_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_stock',
            name='stock_date',
            field=models.DateField(auto_now=True),
        ),
    ]
