# Generated by Django 5.1.6 on 2025-02-06 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_alter_tbl_stock_stock_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_booking',
            name='user',
        ),
    ]
