# Generated by Django 5.1.6 on 2025-02-06 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_remove_tbl_booking_user'),
        ('User', '0003_tbl_booking_alter_tbl_complaint_booking_tbl_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_booking',
        ),
    ]
