# Generated by Django 5.1.6 on 2025-02-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_delete_tbl_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_product',
            name='brand',
        ),
    ]
