# Generated by Django 5.1.4 on 2025-01-09 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_subcategory'),
        ('Guest', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=30)),
                ('shop_email', models.CharField(max_length=30)),
                ('shop_password', models.CharField(max_length=30)),
                ('shop_address', models.CharField(max_length=30)),
                ('shop_contact', models.CharField(max_length=30)),
                ('shop_logo', models.FileField(upload_to='Assets/File/Shop')),
                ('shop_proof', models.FileField(upload_to='Assets/File/Shop')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
