# Generated by Django 5.1.6 on 2025-02-10 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_delete_tbl_booking'),
        ('User', '0003_tbl_booking_alter_tbl_complaint_booking_tbl_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='booking',
        ),
        migrations.AddField(
            model_name='tbl_complaint',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Shop.tbl_product'),
            preserve_default=False,
        ),
    ]
