# Generated by Django 5.1.6 on 2025-02-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_tbl_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_rating',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tbl_rating',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_cart',
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
        migrations.DeleteModel(
            name='tbl_rating',
        ),
    ]
